# Generated by Django 5.2 on 2025-05-13 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_recurso_remove_estudiante_nombre_completo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacion',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='estudiante',
        ),
        migrations.DeleteModel(
            name='Cursos',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='user',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='docente',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='docente',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='user',
        ),
        migrations.DeleteModel(
            name='Calificacion',
        ),
        migrations.DeleteModel(
            name='Docente',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
