# Generated by Django 5.2 on 2025-04-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Código de categoría')),
                ('nombre', models.CharField(max_length=50)),
                ('cupos', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
